// Generated by scripts/make-illustrations.py: each illustration's size in points (the file is 3x).
export const ILLUSTRATIONS = {
  'ill-01-splash': [224, 256],
  'ill-03-no-tune': [128, 160],
  'ill-04-mic-off': [117, 160],
  'ill-06-split': [240, 170],
  'ill-07-splitting': [146, 160],
  'ill-08-no-songs': [200, 139],
  'ill-09-pro': [137, 180],
  'ill-10-headphones': [116, 140],
  'ill-11-live': [109, 160],
  'ill-12-share': [156, 200],
  'ill-13-keytar': [105, 160],
} as const;
export type Illustration = keyof typeof ILLUSTRATIONS;
