// More arrangement styles (same format as styles.ts). Each lists a few other lead instruments (`alts`)
// that suit it, so "More" can offer the same style with a different voice on the tune.
import type { Style } from './styles';

const S = (s: Style): Style => s;

export const MORE_STYLES: readonly Style[] = [
  S({ id: 'rnb', name: 'R&B', emoji: '', blurb: 'Laid-back groove · E-piano · sub', bpm: [60, 95], mood: 'any', kit: 'lofi', swing: 0.08,
    groove: { kick: 'x......x..x.....', snare: '....x.......x...', hat: 'x-x-x-xox-x-x-xo' },
    bass: { preset: 'sub', rhythm: 'kick' }, chords: { preset: 'keys', rhythm: 'comp', sevenths: true },
    lead: { preset: 'vibes', center: 72 }, alts: ['whistle', 'flute', 'keys'], mix: { drums: 0.8, bass: 0.8, chords: 0.6, lead: 0.8 } }),
  S({ id: 'rock', name: 'Rock', emoji: '', blurb: 'Live drums · guitars · bass', bpm: [100, 150], mood: 'any', kit: 'rock', swing: 0,
    groove: { kick: 'x.....x.x.......', snare: '....x.......x...', hat: 'x.x.x.x.x.x.x.x.' }, fill: { snare: '....x.......xxxx' },
    bass: { preset: 'fingerbass', rhythm: 'eighths' }, chords: { preset: 'pluck', rhythm: 'strum' },
    lead: { preset: 'synthbrass', center: 67 }, alts: ['supersaw', 'organ', 'violin'], mix: { drums: 0.85, bass: 0.8, chords: 0.65, lead: 0.75 } }),
  S({ id: 'reggae', name: 'Reggae', emoji: '', blurb: 'One drop · off-beat organ · deep bass', bpm: [65, 92], mood: 'any', kit: 'afro', swing: 0.1,
    groove: { kick: '........x.......', snare: '........x.......', hat: 'x.x.x.x.x.x.x.x.' },
    bass: { preset: 'sub', rhythm: 'kick' }, chords: { preset: 'organ', rhythm: 'skank' },
    lead: { preset: 'harmonica', center: 69 }, alts: ['pluck', 'clarinet', 'steel'], mix: { drums: 0.8, bass: 0.9, chords: 0.55, lead: 0.75 } }),
  S({ id: 'afro', name: 'Afrobeat', emoji: '', blurb: 'Bouncy drums · kalimba · warm bass', bpm: [95, 118], mood: 'any', kit: 'afro', swing: 0.06,
    groove: { kick: 'x..x..x...x.....', snare: '....x..-....x..-', hat: 'xoxoxoxoxoxoxoxo' },
    bass: { preset: 'bass', rhythm: 'kick' }, chords: { preset: 'kalimba', rhythm: 'arp' },
    lead: { preset: 'steel', center: 72 }, alts: ['pluck', 'panflute', 'sax'], mix: { drums: 0.85, bass: 0.8, chords: 0.55, lead: 0.75 } }),
  S({ id: 'reggaeton', name: 'Reggaeton', emoji: '', blurb: 'Dembow beat · 808 · synth stabs', bpm: [86, 102], mood: 'minor', kit: 'reggaeton', swing: 0,
    groove: { kick: 'x...x...x...x...', snare: '...x..x....x..x.', hat: '..x...x...x...x.' },
    bass: { preset: 'bass808', rhythm: 'kick' }, chords: { preset: 'polysynth', rhythm: 'stabs' },
    lead: { preset: 'pluck', center: 69 }, alts: ['whistle', 'bell', 'synthbrass'], mix: { drums: 0.85, bass: 0.85, chords: 0.5, lead: 0.75 } }),
  S({ id: 'funk', name: 'Funk', emoji: '', blurb: 'Tight groove · slap bass · horns', bpm: [95, 122], mood: 'any', kit: 'funk', swing: 0.05,
    groove: { kick: 'x..x..x...x..x..', snare: '....x..-....x...', hat: 'xoxoxoxoxoxoxoxo' }, fill: { snare: '....x..-....x.xx' },
    bass: { preset: 'fingerbass', rhythm: 'eighths' }, chords: { preset: 'keys', rhythm: 'stabs', sevenths: true },
    lead: { preset: 'synthbrass', center: 70 }, alts: ['brass', 'sax', 'organ'], mix: { drums: 0.85, bass: 0.85, chords: 0.55, lead: 0.75 } }),
  S({ id: 'jazz', name: 'Jazz', emoji: '', blurb: 'Brushes · walking bass · piano', bpm: [80, 140], mood: 'any', kit: 'jazz', swing: 0.22,
    groove: { kick: 'x.......x.......', snare: '....-.......-...', hat: 'x..x.x..x..x.x..' },
    bass: { preset: 'upright', rhythm: 'walk' }, chords: { preset: 'piano', rhythm: 'comp', sevenths: true },
    lead: { preset: 'sax', center: 67 }, alts: ['clarinet', 'vibes', 'brass'], mix: { drums: 0.7, bass: 0.85, chords: 0.6, lead: 0.8 } }),
  S({ id: 'ballad', name: 'Piano Ballad', emoji: '', blurb: 'Soft piano · strings · gentle beat', bpm: [58, 86], mood: 'any', kit: 'acoustic', swing: 0,
    groove: { kick: 'x.......x.......', snare: '........-.......', hat: '................' },
    bass: { preset: 'sub', rhythm: 'sustain' }, chords: { preset: 'piano', rhythm: 'arp' },
    lead: { preset: 'violin', center: 72 }, alts: ['strings', 'flute', 'choir'], mix: { drums: 0.5, bass: 0.7, chords: 0.7, lead: 0.8 } }),
  S({ id: 'edm', name: 'EDM', emoji: '', blurb: 'Big kick · supersaw · reese bass', bpm: [120, 132], mood: 'any', kit: 'electro', swing: 0,
    groove: { kick: 'x...x...x...x...', snare: '....x.......x...', hat: '..o...o...o...o.' }, fill: { snare: '....x...x.x.xxxx' },
    bass: { preset: 'reese', rhythm: 'offbeat' }, chords: { preset: 'supersaw', rhythm: 'stabs' },
    lead: { preset: 'polysynth', center: 72 }, alts: ['supersaw', 'chip', 'whistle'], mix: { drums: 0.85, bass: 0.75, chords: 0.5, lead: 0.7 } }),
  S({ id: 'drill', name: 'Drill', emoji: '', blurb: 'Sliding 808s · sharp hats · dark keys', bpm: [136, 146], mood: 'minor', kit: 'drill', swing: 0,
    groove: { kick: 'x......x...x....', snare: '......x.......x.', hat: 'x..x..x.x..x..x.' },
    bass: { preset: 'bass808', rhythm: 'long' }, chords: { preset: 'strings', rhythm: 'sustain' },
    lead: { preset: 'musicbox', center: 76 }, alts: ['bell', 'piano', 'choir'], mix: { drums: 0.85, bass: 0.85, chords: 0.45, lead: 0.75 } }),
  S({ id: 'garage', name: 'UK Garage', emoji: '', blurb: 'Two-step · swung hats · organ bass', bpm: [128, 136], mood: 'any', kit: 'garage', swing: 0.15,
    groove: { kick: 'x.........x.....', snare: '....x.......x...', hat: '..x...x...x...x.' },
    bass: { preset: 'reese', rhythm: 'offbeat' }, chords: { preset: 'keys', rhythm: 'stabs', sevenths: true },
    lead: { preset: 'polysynth', center: 72 }, alts: ['whistle', 'organ', 'bell'], mix: { drums: 0.85, bass: 0.8, chords: 0.5, lead: 0.7 } }),
  S({ id: 'synthwave', name: 'Synthwave', emoji: '', blurb: '80s drums · pads · driving bass', bpm: [85, 118], mood: 'any', kit: 'retro', swing: 0,
    groove: { kick: 'x...x...x...x...', snare: '....x.......x...', hat: 'x.x.x.x.x.x.x.x.' },
    bass: { preset: 'bass', rhythm: 'eighths' }, chords: { preset: 'pad', rhythm: 'sustain' },
    lead: { preset: 'supersaw', center: 72 }, alts: ['chip', 'synthbrass', 'polysynth'], mix: { drums: 0.8, bass: 0.75, chords: 0.6, lead: 0.7 } }),
  S({ id: 'folk', name: 'Folk', emoji: '', blurb: 'Ukulele · stomps · harmonica', bpm: [88, 130], mood: 'major', kit: 'acoustic', swing: 0.05,
    groove: { kick: 'x.......x.......', snare: '....x.......x...', hat: '................' },
    bass: { preset: 'upright', rhythm: 'kick' }, chords: { preset: 'ukulele', rhythm: 'strum' },
    lead: { preset: 'harmonica', center: 69 }, alts: ['whistle', 'accordion', 'violin'], mix: { drums: 0.7, bass: 0.8, chords: 0.65, lead: 0.75 } }),
  S({ id: 'ambient', name: 'Ambient', emoji: '', blurb: 'No drums · pads · music box', bpm: [60, 92], mood: 'any', kit: '808', swing: 0,
    groove: { kick: '................', snare: '................', hat: '................' },
    bass: { preset: 'sub', rhythm: 'sustain' }, chords: { preset: 'pad', rhythm: 'sustain' },
    lead: { preset: 'musicbox', center: 76 }, alts: ['harp', 'vibes', 'choir'], mix: { drums: 0.5, bass: 0.7, chords: 0.7, lead: 0.8 } }),
];
